# Generated by Django 5.2.17 on 2026-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='main_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
