# Generated by Django 5.2.17 on 2026-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=50)),
                ('end_year', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
